#!/usr/bin/env python

import sys, argparse, os, subprocess

def main(args):
  
  # copy files recursively to remote host. NB. will fail if password required.
  os.system('scp -r %s %s:~/.ecs-print' % (args.file, args.host))

  # connect to remote
  ssh = subprocess.Popen(['ssh', '-T', args.host], stdin=subprocess.PIPE, stdout=subprocess.PIPE)

  # print files. -r removes them afterwards
  cmd = 'lpr -P mfp0 -r %s' % args.file
  cmd = 'echo "%s"' % cmd # REMOVE when not debugging
  output = ssh.communicate(cmd)

  # display stdout from remote
  print(output[0].decode("utf-8"))
 

# Standard boilerplate to call the main() function to begin the program
if __name__ == '__main__':
  parser = argparse.ArgumentParser( description = "Prints files from remote printers over ssh" )

  parser.add_argument(
                      "host",
                      help = "Remote host to ssh into. e.g. m11dtf@ecs.ox.ac.uk (NB. password prompt for ssh will fail)",
                      metavar = "user@hostname")
  parser.add_argument(
                      "file",
                      help="File(s) to print.",
                      metavar = "file")
  args = parser.parse_args()
  
  main(args)